version: '3'

# Infra
services:    
    db:
        build: ./docker/mysql
        image: mysql:5.6
        restart: always
        container_name: db_host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/log:/var/log/mysql
        ports:
            - 4306:3306
        networks:
            app_net:
                ipv4_address: 172.20.0.2
    ec2:
        build: ./docker/aws
        image: amazonlinux:2018.03
        container_name: ec2
        restart: always
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./docker/aws/home:/home/ec2-user
        ports:
            - "8888:80"
        tty: true
        networks:
            app_net:
                ipv4_address: 172.20.0.3

# Network
networks:
    app_net:
      driver: bridge
      ipam:
        driver: default
        config:
            - subnet: 172.20.0.0/16